import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/component/header/Header";
import MainLayout from "@/component/layouts/MainLayout";
import Footer from "@/component/footer/Footer";
import ToastProvider from "@/Provider/toastifyProvider";
import PortfolioProvider from "@/Provider/Provider";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className}`}>
    <PortfolioProvider>
    <ToastProvider/>
      <MainLayout>
      <Header/>
      {children}
      <Footer/>
    </MainLayout>
    </PortfolioProvider>
    </body>
    </html>
  );
}
